version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis
  readtemps:
    build: .
    command: python manage.py streamtemps
    volumes:
      - .:/code
    ports:
      - 5157:5157/udp
    links:
      - redis